---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.
<<<<<<< HEAD


*Answers*
This is a line from RStudio

*Problems*
+ We ran into a problem where we are unable to push our commits to Git. It says something about password authentication expiring in 2021.
  + We looked up the problem and discovered that we must create personal access tokens
+ We ran into a problem where we are unable to push our changes because we "don't have local access to some reference material"
  +



This is a change from rStudio

Problems 
1. I had to install git and connect my rstudio to github
2. For some reason we didn't have to authorize the commit, it just immediately changed the file

>**_This is a line from RStudio -gabriel_**
### More problems:
  * We had to do a 'git config pull.rebase false' before we could pull
  * We had to generate a personal access token and install the gitcreds package
